/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MaxRouteImport } from './routes/max'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PromoIndexRouteImport } from './routes/promo.index'
import { Route as MaxIndexRouteImport } from './routes/max.index'
import { Route as PromoSlugRouteImport } from './routes/promo.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as MaxCheckoutRouteImport } from './routes/max.checkout'
import { Route as MaxCatalogRouteImport } from './routes/max.catalog'
import { Route as MaxCartRouteImport } from './routes/max.cart'
import { Route as MaxOrderIndexRouteImport } from './routes/max.order.index'
import { Route as MaxProductSlugRouteImport } from './routes/max.product.$slug'
import { Route as MaxOrderIdRouteImport } from './routes/max.order.$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MaxRoute = MaxRouteImport.update({
  id: '/max',
  path: '/max',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromoIndexRoute = PromoIndexRouteImport.update({
  id: '/promo/',
  path: '/promo/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaxIndexRoute = MaxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MaxRoute,
} as any)
const PromoSlugRoute = PromoSlugRouteImport.update({
  id: '/promo/$slug',
  path: '/promo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MaxCheckoutRoute = MaxCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MaxRoute,
} as any)
const MaxCatalogRoute = MaxCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => MaxRoute,
} as any)
const MaxCartRoute = MaxCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MaxRoute,
} as any)
const MaxOrderIndexRoute = MaxOrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => MaxRoute,
} as any)
const MaxProductSlugRoute = MaxProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => MaxRoute,
} as any)
const MaxOrderIdRoute = MaxOrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => MaxRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/max': typeof MaxRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/max/cart': typeof MaxCartRoute
  '/max/catalog': typeof MaxCatalogRoute
  '/max/checkout': typeof MaxCheckoutRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/promo/$slug': typeof PromoSlugRoute
  '/max/': typeof MaxIndexRoute
  '/promo/': typeof PromoIndexRoute
  '/max/order/$id': typeof MaxOrderIdRoute
  '/max/product/$slug': typeof MaxProductSlugRoute
  '/max/order/': typeof MaxOrderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/max/cart': typeof MaxCartRoute
  '/max/catalog': typeof MaxCatalogRoute
  '/max/checkout': typeof MaxCheckoutRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/promo/$slug': typeof PromoSlugRoute
  '/max': typeof MaxIndexRoute
  '/promo': typeof PromoIndexRoute
  '/max/order/$id': typeof MaxOrderIdRoute
  '/max/product/$slug': typeof MaxProductSlugRoute
  '/max/order': typeof MaxOrderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/catalog': typeof CatalogRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/max': typeof MaxRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/max/cart': typeof MaxCartRoute
  '/max/catalog': typeof MaxCatalogRoute
  '/max/checkout': typeof MaxCheckoutRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$slug': typeof ProductSlugRoute
  '/promo/$slug': typeof PromoSlugRoute
  '/max/': typeof MaxIndexRoute
  '/promo/': typeof PromoIndexRoute
  '/max/order/$id': typeof MaxOrderIdRoute
  '/max/product/$slug': typeof MaxProductSlugRoute
  '/max/order/': typeof MaxOrderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/delivery'
    | '/max'
    | '/privacy'
    | '/reviews'
    | '/search'
    | '/max/cart'
    | '/max/catalog'
    | '/max/checkout'
    | '/order/$id'
    | '/product/$slug'
    | '/promo/$slug'
    | '/max/'
    | '/promo/'
    | '/max/order/$id'
    | '/max/product/$slug'
    | '/max/order/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/delivery'
    | '/privacy'
    | '/reviews'
    | '/search'
    | '/max/cart'
    | '/max/catalog'
    | '/max/checkout'
    | '/order/$id'
    | '/product/$slug'
    | '/promo/$slug'
    | '/max'
    | '/promo'
    | '/max/order/$id'
    | '/max/product/$slug'
    | '/max/order'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/catalog'
    | '/checkout'
    | '/delivery'
    | '/max'
    | '/privacy'
    | '/reviews'
    | '/search'
    | '/max/cart'
    | '/max/catalog'
    | '/max/checkout'
    | '/order/$id'
    | '/product/$slug'
    | '/promo/$slug'
    | '/max/'
    | '/promo/'
    | '/max/order/$id'
    | '/max/product/$slug'
    | '/max/order/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CatalogRoute: typeof CatalogRoute
  CheckoutRoute: typeof CheckoutRoute
  DeliveryRoute: typeof DeliveryRoute
  MaxRoute: typeof MaxRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  SearchRoute: typeof SearchRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSlugRoute: typeof ProductSlugRoute
  PromoSlugRoute: typeof PromoSlugRoute
  PromoIndexRoute: typeof PromoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/max': {
      id: '/max'
      path: '/max'
      fullPath: '/max'
      preLoaderRoute: typeof MaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promo/': {
      id: '/promo/'
      path: '/promo'
      fullPath: '/promo/'
      preLoaderRoute: typeof PromoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/max/': {
      id: '/max/'
      path: '/'
      fullPath: '/max/'
      preLoaderRoute: typeof MaxIndexRouteImport
      parentRoute: typeof MaxRoute
    }
    '/promo/$slug': {
      id: '/promo/$slug'
      path: '/promo/$slug'
      fullPath: '/promo/$slug'
      preLoaderRoute: typeof PromoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/max/checkout': {
      id: '/max/checkout'
      path: '/checkout'
      fullPath: '/max/checkout'
      preLoaderRoute: typeof MaxCheckoutRouteImport
      parentRoute: typeof MaxRoute
    }
    '/max/catalog': {
      id: '/max/catalog'
      path: '/catalog'
      fullPath: '/max/catalog'
      preLoaderRoute: typeof MaxCatalogRouteImport
      parentRoute: typeof MaxRoute
    }
    '/max/cart': {
      id: '/max/cart'
      path: '/cart'
      fullPath: '/max/cart'
      preLoaderRoute: typeof MaxCartRouteImport
      parentRoute: typeof MaxRoute
    }
    '/max/order/': {
      id: '/max/order/'
      path: '/order'
      fullPath: '/max/order/'
      preLoaderRoute: typeof MaxOrderIndexRouteImport
      parentRoute: typeof MaxRoute
    }
    '/max/product/$slug': {
      id: '/max/product/$slug'
      path: '/product/$slug'
      fullPath: '/max/product/$slug'
      preLoaderRoute: typeof MaxProductSlugRouteImport
      parentRoute: typeof MaxRoute
    }
    '/max/order/$id': {
      id: '/max/order/$id'
      path: '/order/$id'
      fullPath: '/max/order/$id'
      preLoaderRoute: typeof MaxOrderIdRouteImport
      parentRoute: typeof MaxRoute
    }
  }
}

interface MaxRouteChildren {
  MaxCartRoute: typeof MaxCartRoute
  MaxCatalogRoute: typeof MaxCatalogRoute
  MaxCheckoutRoute: typeof MaxCheckoutRoute
  MaxIndexRoute: typeof MaxIndexRoute
  MaxOrderIdRoute: typeof MaxOrderIdRoute
  MaxProductSlugRoute: typeof MaxProductSlugRoute
  MaxOrderIndexRoute: typeof MaxOrderIndexRoute
}

const MaxRouteChildren: MaxRouteChildren = {
  MaxCartRoute: MaxCartRoute,
  MaxCatalogRoute: MaxCatalogRoute,
  MaxCheckoutRoute: MaxCheckoutRoute,
  MaxIndexRoute: MaxIndexRoute,
  MaxOrderIdRoute: MaxOrderIdRoute,
  MaxProductSlugRoute: MaxProductSlugRoute,
  MaxOrderIndexRoute: MaxOrderIndexRoute,
}

const MaxRouteWithChildren = MaxRoute._addFileChildren(MaxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CatalogRoute: CatalogRoute,
  CheckoutRoute: CheckoutRoute,
  DeliveryRoute: DeliveryRoute,
  MaxRoute: MaxRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  SearchRoute: SearchRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSlugRoute: ProductSlugRoute,
  PromoSlugRoute: PromoSlugRoute,
  PromoIndexRoute: PromoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
